/// Scaffold devcontainer-guard files into a project.
///
/// Two modes:
/// - New project (no .devcontainer/): creates everything from scratch
/// - Existing project (.devcontainer/ exists): creates devg.toml + overlay compose,
///   updates devcontainer.json
use crate::config::ComposeConfig;
use anyhow::{Context, Result};
use std::path::Path;

pub const OVERLAY_FILENAME: &str = "docker-compose.devg.yml";

pub fn run(project_dir: &str, yes: bool) -> Result<()> {
    let project = Path::new(project_dir);
    let devcontainer_dir = project.join(".devcontainer");

    if devcontainer_dir.exists() {
        run_existing(project, &devcontainer_dir, yes)
    } else {
        run_new(project, &devcontainer_dir)
    }
}

fn confirm(prompt: &str) -> bool {
    use std::io::Write;
    print!("{prompt} [Y/n] ");
    std::io::stdout().flush().ok();
    let mut input = String::new();
    if std::io::stdin().read_line(&mut input).is_err() {
        return false;
    }
    let input = input.trim().to_lowercase();
    input.is_empty() || input == "y" || input == "yes"
}

/// Read the service name from devcontainer.json. Defaults to "app".
pub fn read_service_name(devcontainer_dir: &Path) -> Result<String> {
    let path = devcontainer_dir.join("devcontainer.json");
    let content =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    let json: serde_json::Value =
        serde_json::from_str(&content).with_context(|| format!("parsing {}", path.display()))?;
    Ok(json["service"].as_str().unwrap_or("app").to_string())
}

/// Derive a unique /24 subnet from the project directory path.
/// Returns a prefix like "172.28.0" (without trailing dot).
/// Range: 172.18.0.0/24 - 172.31.255.0/24 (avoids Docker's default 172.17.x.x).
pub fn derive_subnet(project_dir: &Path) -> String {
    let path = project_dir
        .canonicalize()
        .unwrap_or_else(|_| project_dir.to_path_buf());
    let path_str = path.to_string_lossy();

    let mut hash: u32 = 0;
    for byte in path_str.bytes() {
        hash = hash.wrapping_mul(31).wrapping_add(byte as u32);
    }

    let second = 18 + (hash % 14) as u8; // 18-31
    let third = ((hash >> 8) % 256) as u8; // 0-255
    format!("172.{second}.{third}")
}

/// Generate the overlay compose YAML for the devg sidecar.
pub fn generate_overlay(
    service_name: &str,
    compose: &ComposeConfig,
    cli_tools: &[String],
    subnet_prefix: &str,
) -> String {
    let image_yaml = compose.image_yaml("    ");
    let cli_volumes = if cli_tools.is_empty() {
        String::new()
    } else {
        let mut mounts: Vec<String> = cli_tools
            .iter()
            .map(|name| format!("      - ./{name}-shim.sh:/usr/local/bin/{name}:ro"))
            .collect();
        // Mount devg binary from sidecar via shared volume
        mounts.push("      - devg-bin:/opt/devg:ro".to_string());
        format!("\n    volumes:\n{}", mounts.join("\n"))
    };
    let app_ip = format!("{subnet_prefix}.2");
    let sidecar_ip = format!("{subnet_prefix}.3");
    let subnet = format!("{subnet_prefix}.0/24");
    format!(
        r#"# Generated by devg — DO NOT EDIT. Regenerated on each `devg init-env` run.
# Adds network isolation, DNS filtering, and MCP proxy.
# Merged with your existing docker-compose via dockerComposeFile array in devcontainer.json.
# This file MUST be last in the array so its settings take precedence.
services:
  # Adds proxy env vars and DNS to your existing service
  {service_name}:
    environment:
      # Use static IP because app DNS goes through devg (hostnames won't resolve)
      HTTP_PROXY: http://{sidecar_ip}:3128
      HTTPS_PROXY: http://{sidecar_ip}:3128
      http_proxy: http://{sidecar_ip}:3128
      https_proxy: http://{sidecar_ip}:3128
      NO_PROXY: localhost,127.0.0.1
      no_proxy: localhost,127.0.0.1
    # DNS goes through devg's filtered forwarder (only resolves allowed domains)
    dns:
      - {sidecar_ip}
    networks:
      devg_sandbox:
        ipv4_address: {app_ip}{cli_volumes}
    depends_on:
      devg:
        condition: service_healthy

  # Proxy sidecar: domain proxy (:3128), DNS forwarder (:53), MCP proxy (:3129)
  devg:
{image_yaml}
    volumes:
      - ./devg.toml:/etc/devg/config.toml:ro
      - ${{HOME}}/.devg/auth:/etc/devg/auth
      - proxy-logs:/var/log/devg
      - devg-bin:/opt/devg
      - ..:/workspace:ro
    entrypoint: ["sh", "-c", "cp /usr/local/bin/devg /opt/devg/devg && exec devg proxy"]
    env_file:
      - path: .env
        required: false
    networks:
      devg_sandbox:
        ipv4_address: {sidecar_ip}
      devg_external:
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "devg", "check", "--proxy"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  proxy-logs:
  devg-bin:

# Static subnet so we can use fixed IPs for DNS and proxy references.
# Internal to Docker, not your host network.
networks:
  devg_sandbox:
    internal: true  # no default gateway, no route to internet
    ipam:
      config:
        - subnet: {subnet}
  devg_external:
    driver: bridge
"#
    )
}

/// Append devg-generated entries to .gitignore if not already present.
pub fn gitignore_overlay(project_dir: &Path) -> Result<()> {
    let gitignore_path = project_dir.join(".gitignore");
    let entries = [
        format!(".devcontainer/{OVERLAY_FILENAME}"),
        ".devcontainer/.env".to_string(),
    ];

    let existing = if gitignore_path.exists() {
        std::fs::read_to_string(&gitignore_path)?
    } else {
        String::new()
    };

    let new_entries: Vec<&str> = entries
        .iter()
        .filter(|e| !existing.lines().any(|line| line.trim() == e.as_str()))
        .map(|e| e.as_str())
        .collect();

    if new_entries.is_empty() {
        return Ok(());
    }

    let separator = if existing.is_empty() || existing.ends_with('\n') {
        ""
    } else {
        "\n"
    };
    let block = new_entries.join("\n");
    std::fs::write(
        &gitignore_path,
        format!("{existing}{separator}\n# Generated by devg\n{block}\n"),
    )?;
    Ok(())
}

/// Existing project: create config, generate overlay, update devcontainer.json.
fn run_existing(project: &Path, devcontainer_dir: &Path, yes: bool) -> Result<()> {
    let devcontainer_json_path = devcontainer_dir.join("devcontainer.json");
    if !devcontainer_json_path.exists() {
        anyhow::bail!(
            ".devcontainer/ exists but has no devcontainer.json at {}",
            devcontainer_json_path.display()
        );
    }

    let devg_toml_path = devcontainer_dir.join("devg.toml");
    if devg_toml_path.exists() {
        anyhow::bail!(
            "devg.toml already exists at {}. Remove it to re-initialize.",
            devg_toml_path.display()
        );
    }

    let dc_content = std::fs::read_to_string(&devcontainer_json_path)?;
    let dc_json: serde_json::Value = serde_json::from_str(&dc_content)?;

    let image_based = dc_json.get("image").is_some() && dc_json.get("dockerComposeFile").is_none();

    // If image-based, ask to convert to compose mode
    if image_based {
        let image = dc_json["image"]
            .as_str()
            .unwrap_or("mcr.microsoft.com/devcontainers/base:ubuntu");

        println!();
        println!(
            "  Your devcontainer uses \x1b[1mimage\x1b[0m mode, but devg requires Docker Compose."
        );
        println!("  I'll convert it for you:");
        println!();
        println!("    \x1b[32m+\x1b[0m Create docker-compose.yml  (image: {image})");
        println!(
            "    \x1b[33m~\x1b[0m Update devcontainer.json   (add service, workspaceFolder, dockerComposeFile)"
        );
        println!(
            "    \x1b[31m-\x1b[0m Remove \"image\" field        (moved to docker-compose.yml)"
        );
        println!();

        if !yes && !confirm("  Proceed?") {
            anyhow::bail!("aborted");
        }

        let compose_path = devcontainer_dir.join("docker-compose.yml");
        if !compose_path.exists() {
            write_file(
                &compose_path,
                &format!(
                    "services:\n  app:\n    image: {image}\n    volumes:\n      - ..:/workspace:cached\n    command: sleep infinity\n"
                ),
            )?;
        }
    }

    let service_name = if image_based {
        "app".to_string()
    } else {
        read_service_name(devcontainer_dir)?
    };

    let compose_files: Vec<String> = if image_based {
        vec!["docker-compose.yml".to_string()]
    } else if let Some(arr) = dc_json["dockerComposeFile"].as_array() {
        arr.iter()
            .filter_map(|v| v.as_str().map(String::from))
            .collect()
    } else if let Some(s) = dc_json["dockerComposeFile"].as_str() {
        vec![s.to_string()]
    } else {
        vec!["docker-compose.yml".to_string()]
    };

    // Write devg.toml (auto-detects CLI tools like gh)
    let config_content = generate_config(DEFAULT_DOMAINS);
    write_file(&devg_toml_path, &config_content)?;

    // Parse back to get detected CLI tools for the overlay
    let detected_tools: Vec<String> = detect_cli_tools()
        .iter()
        .map(|t| t.name.to_string())
        .collect();

    // Generate overlay (using default ComposeConfig — user can customize in devg.toml later)
    let overlay_path = devcontainer_dir.join(OVERLAY_FILENAME);
    let compose_config = ComposeConfig::default();
    let subnet_prefix = derive_subnet(project);
    write_file(
        &overlay_path,
        &generate_overlay(
            &service_name,
            &compose_config,
            &detected_tools,
            &subnet_prefix,
        ),
    )?;

    // Update devcontainer.json
    let mut dc_obj = dc_json.clone();

    // Remove image field (now in docker-compose.yml)
    if image_based {
        dc_obj.as_object_mut().unwrap().remove("image");
    }

    let mut all_compose: Vec<serde_json::Value> = compose_files
        .iter()
        .map(|f| serde_json::Value::String(f.clone()))
        .collect();
    all_compose.push(serde_json::Value::String(OVERLAY_FILENAME.to_string()));
    dc_obj["dockerComposeFile"] = serde_json::Value::Array(all_compose);
    dc_obj["service"] = serde_json::Value::String(service_name);
    dc_obj["workspaceFolder"] = serde_json::Value::String("/workspace".to_string());

    let mut notes: Vec<String> = Vec::new();

    if dc_obj.get("initializeCommand").is_some() {
        notes.push(
            "initializeCommand already set. Add `devg init-env` to your existing command."
                .to_string(),
        );
    } else {
        dc_obj["initializeCommand"] = serde_json::Value::String("devg init-env".to_string());
    }

    let updated = serde_json::to_string_pretty(&dc_obj)?;
    write_file(&devcontainer_json_path, &format!("{updated}\n"))?;

    // Add overlay to .gitignore
    gitignore_overlay(project)?;

    println!();
    println!("Created .devcontainer/devg.toml");
    println!("Created .devcontainer/{OVERLAY_FILENAME} (generated, gitignored)");
    println!("Updated .devcontainer/devcontainer.json");

    for note in &notes {
        println!();
        println!("  NOTE: {note}");
    }

    println!();
    println!("Next:");
    println!("  devcontainer up");
    println!("  devg status   # verify everything is wired correctly");

    Ok(())
}

/// New project: create everything from scratch.
fn run_new(project: &Path, devcontainer_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(devcontainer_dir)?;

    let project_name = project
        .canonicalize()
        .ok()
        .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
        .unwrap_or_else(|| "my-project".to_string());

    write_file(
        &devcontainer_dir.join("devg.toml"),
        &generate_config(DEFAULT_DOMAINS),
    )?;
    write_file(
        &devcontainer_dir.join("docker-compose.yml"),
        &generate_app_compose(&project_name),
    )?;
    write_file(
        &devcontainer_dir.join("devcontainer.json"),
        &generate_devcontainer_json(&project_name),
    )?;

    // Generate the overlay so things work immediately
    let compose_config = ComposeConfig::default();
    let subnet_prefix = derive_subnet(project);
    let detected_tools: Vec<String> = detect_cli_tools()
        .iter()
        .map(|t| t.name.to_string())
        .collect();
    write_file(
        &devcontainer_dir.join(OVERLAY_FILENAME),
        &generate_overlay("app", &compose_config, &detected_tools, &subnet_prefix),
    )?;

    // Add overlay to .gitignore
    gitignore_overlay(project)?;

    println!("Created .devcontainer/ with:");
    println!("  devg.toml            - guard config (edit allowed domains here)");
    println!("  docker-compose.yml   - app container definition");
    println!("  devcontainer.json    - devcontainer config");
    println!("  {OVERLAY_FILENAME}   - devg sidecar (generated, gitignored)");
    println!();
    println!("Next steps:");
    println!("  1. Review devg.toml and adjust allowed domains");
    println!("  2. Run: devcontainer up");

    Ok(())
}

const DEFAULT_DOMAINS: &[&str] = &[
    // GitHub
    "github.com",
    "*.github.com",
    "*.githubusercontent.com",
    // AI
    "anthropic.com",
    "*.anthropic.com",
    "claude.ai",
    "*.claude.ai",
    "claude.com",
    "*.claude.com",
    "openai.com",
    "*.openai.com",
    "generativelanguage.googleapis.com",
    // APT
    "*.ubuntu.com",
    "*.debian.org",
    // Ruby
    "rubygems.org",
    "*.rubygems.org",
    "bundler.io",
    "*.ruby-lang.org",
    "rubyonrails.org",
    "*.rubyonrails.org",
    // Node
    "*.npmjs.org",
    "*.npmjs.com",
    "nodejs.org",
    "*.yarnpkg.com",
    // Rust
    "crates.io",
    "*.crates.io",
    "rustup.rs",
    "*.rust-lang.org",
    // Python
    "pypi.org",
    "*.pypi.org",
    "*.pythonhosted.org",
    // Go
    "proxy.golang.org",
    "sum.golang.org",
    "storage.googleapis.com",
    // Java
    "repo.maven.apache.org",
    "*.maven.org",
    "plugins.gradle.org",
    "services.gradle.org",
    "downloads.gradle-dn.com",
    // CocoaPods
    "cocoapods.org",
    "*.cocoapods.org",
];

struct DetectedTool {
    name: &'static str,
    env: &'static [&'static str],
    allow: &'static [&'static str],
}

const DETECTABLE_TOOLS: &[DetectedTool] = &[DetectedTool {
    name: "gh",
    env: &["GH_TOKEN"],
    allow: &["*"],
}];

fn detect_cli_tools() -> Vec<&'static DetectedTool> {
    DETECTABLE_TOOLS
        .iter()
        .filter(|t| {
            std::process::Command::new("which")
                .arg(t.name)
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null())
                .status()
                .is_ok_and(|s| s.success())
        })
        .collect()
}

fn generate_config(domains: &[&str]) -> String {
    let allow_toml = domains
        .iter()
        .map(|d| format!("  \"{d}\""))
        .collect::<Vec<_>>()
        .join(",\n");

    let detected = detect_cli_tools();
    let cli_section = if detected.is_empty() {
        String::new()
    } else {
        let tools: Vec<String> = detected
            .iter()
            .map(|t| {
                let env = t
                    .env
                    .iter()
                    .map(|e| format!("\"{e}\""))
                    .collect::<Vec<_>>()
                    .join(", ");
                let allow = t
                    .allow
                    .iter()
                    .map(|a| format!("\"{a}\""))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(
                    "\n[[cli.tools]]\nname = \"{}\"\nenv = [{}]\nallow = [{}]",
                    t.name, env, allow
                )
            })
            .collect();
        format!("\n[cli]{}\n", tools.join("\n"))
    };

    format!(
        r#"# devg.toml: devcontainer-guard configuration

[proxy.network]
allow = [
{allow_toml},
]
# deny overrides allow:
# deny = ["gist.github.com"]
{cli_section}"#
    )
}

/// Generate the app-only compose file for new projects.
/// The devg sidecar is in the generated overlay (docker-compose.devg.yml).
fn generate_app_compose(project_name: &str) -> String {
    format!(
        r#"services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspaces/{project_name}:cached
      # 1Password SSH agent (macOS). On Linux, use $SSH_AUTH_SOCK instead.
      - ${{HOME}}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock:/ssh-agent:ro
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    command: sleep infinity
"#
    )
}

fn generate_devcontainer_json(project_name: &str) -> String {
    format!(
        r#"{{
  "name": "{project_name}",
  "dockerComposeFile": ["docker-compose.yml", "{OVERLAY_FILENAME}"],
  "service": "app",
  "workspaceFolder": "/workspaces/{project_name}",
  "initializeCommand": "devg init-env",
  "remoteUser": "vscode"
}}
"#
    )
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    std::fs::write(path, content).with_context(|| format!("writing {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn default_domains_covers_all_ecosystems() {
        let domains = DEFAULT_DOMAINS;
        assert!(domains.contains(&"github.com"));
        assert!(domains.contains(&"anthropic.com"));
        assert!(domains.contains(&"crates.io"));
        assert!(domains.contains(&"*.npmjs.org"));
        assert!(domains.contains(&"pypi.org"));
        assert!(domains.contains(&"proxy.golang.org"));
        assert!(domains.contains(&"rubygems.org"));
        assert!(domains.contains(&"cocoapods.org"));
        assert!(domains.contains(&"repo.maven.apache.org"));
    }

    #[test]
    fn new_project_scaffolds_all_files() {
        let dir = tempdir("scaffold-new");
        run(dir.to_str().unwrap(), true).unwrap();
        let dc = dir.join(".devcontainer");
        assert!(dc.join("devg.toml").exists());
        assert!(dc.join("docker-compose.yml").exists());
        assert!(dc.join("devcontainer.json").exists());
        assert!(dc.join(OVERLAY_FILENAME).exists());

        let config = fs::read_to_string(dc.join("devg.toml")).unwrap();
        assert!(config.contains("allow ="));

        // App compose should NOT contain devg service (it's in the overlay)
        let compose = fs::read_to_string(dc.join("docker-compose.yml")).unwrap();
        assert!(compose.contains("app:"));
        assert!(!compose.contains("devg:"));

        // Overlay should contain devg service
        let overlay = fs::read_to_string(dc.join(OVERLAY_FILENAME)).unwrap();
        assert!(overlay.contains("devg:"));
        assert!(overlay.contains("devg_sandbox:"));

        // devcontainer.json should reference both compose files
        let dcjson: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(dc.join("devcontainer.json")).unwrap())
                .unwrap();
        let compose_arr = dcjson["dockerComposeFile"].as_array().unwrap();
        assert_eq!(compose_arr.len(), 2);
        assert_eq!(compose_arr[0], "docker-compose.yml");
        assert_eq!(compose_arr[1], OVERLAY_FILENAME);

        // .gitignore should contain overlay
        let gitignore = fs::read_to_string(dir.join(".gitignore")).unwrap();
        assert!(gitignore.contains(OVERLAY_FILENAME));

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn existing_project_creates_overlay_and_updates_json() {
        let dir = tempdir("scaffold-existing");
        let dc = dir.join(".devcontainer");
        fs::create_dir_all(&dc).unwrap();
        fs::write(
            dc.join("devcontainer.json"),
            r#"{"service": "myapp", "dockerComposeFile": "compose.yaml"}"#,
        )
        .unwrap();

        run(dir.to_str().unwrap(), true).unwrap();

        assert!(dc.join("devg.toml").exists());
        assert!(dc.join(OVERLAY_FILENAME).exists());
        assert!(!dc.join("docker-compose.yml").exists());

        let overlay = fs::read_to_string(dc.join(OVERLAY_FILENAME)).unwrap();
        assert!(overlay.contains("myapp:"));
        assert!(overlay.contains("devg:"));
        assert!(overlay.contains("devg_sandbox:"));

        // devcontainer.json should be updated with overlay and initializeCommand
        let updated: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(dc.join("devcontainer.json")).unwrap())
                .unwrap();
        let compose_arr = updated["dockerComposeFile"].as_array().unwrap();
        assert_eq!(compose_arr.len(), 2);
        assert_eq!(compose_arr[0], "compose.yaml");
        assert_eq!(compose_arr[1], OVERLAY_FILENAME);
        assert_eq!(updated["initializeCommand"], "devg init-env");

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn existing_project_appends_to_compose_array() {
        let dir = tempdir("scaffold-array");
        let dc = dir.join(".devcontainer");
        fs::create_dir_all(&dc).unwrap();
        fs::write(
            dc.join("devcontainer.json"),
            r#"{"service": "api", "dockerComposeFile": ["docker-compose.yml", "docker-compose.override.yml"]}"#,
        )
        .unwrap();

        run(dir.to_str().unwrap(), true).unwrap();

        let updated: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(dc.join("devcontainer.json")).unwrap())
                .unwrap();
        let compose_arr = updated["dockerComposeFile"].as_array().unwrap();
        assert_eq!(compose_arr.len(), 3);
        assert_eq!(compose_arr[0], "docker-compose.yml");
        assert_eq!(compose_arr[1], "docker-compose.override.yml");
        assert_eq!(compose_arr[2], OVERLAY_FILENAME);

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn existing_project_fails_if_devg_toml_exists() {
        let dir = tempdir("scaffold-exists");
        let dc = dir.join(".devcontainer");
        fs::create_dir_all(&dc).unwrap();
        fs::write(dc.join("devcontainer.json"), r#"{"service": "app"}"#).unwrap();
        fs::write(dc.join("devg.toml"), "").unwrap();

        assert!(run(dir.to_str().unwrap(), true).is_err());
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn existing_project_fails_if_no_devcontainer_json() {
        let dir = tempdir("scaffold-no-json");
        let dc = dir.join(".devcontainer");
        fs::create_dir_all(&dc).unwrap();
        // .devcontainer/ exists but no devcontainer.json

        assert!(run(dir.to_str().unwrap(), true).is_err());
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn overlay_uses_default_service_name() {
        let dir = tempdir("scaffold-default-svc");
        let dc = dir.join(".devcontainer");
        fs::create_dir_all(&dc).unwrap();
        // No "service" field in json
        fs::write(dc.join("devcontainer.json"), r#"{}"#).unwrap();

        run(dir.to_str().unwrap(), true).unwrap();

        let overlay = fs::read_to_string(dc.join(OVERLAY_FILENAME)).unwrap();
        assert!(overlay.contains("app:"));

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn existing_image_based_converts_to_compose() {
        let dir = tempdir("scaffold-image-based");
        let dc = dir.join(".devcontainer");
        fs::create_dir_all(&dc).unwrap();
        fs::write(
            dc.join("devcontainer.json"),
            r#"{"name": "test", "image": "mcr.microsoft.com/devcontainers/base:ubuntu-24.04", "remoteUser": "vscode"}"#,
        )
        .unwrap();

        run(dir.to_str().unwrap(), true).unwrap();

        // docker-compose.yml should be created with the image
        let compose = fs::read_to_string(dc.join("docker-compose.yml")).unwrap();
        assert!(compose.contains("mcr.microsoft.com/devcontainers/base:ubuntu-24.04"));
        assert!(compose.contains("app:"));

        // devcontainer.json should have compose fields, no image
        let updated: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(dc.join("devcontainer.json")).unwrap())
                .unwrap();
        assert!(updated.get("image").is_none());
        assert_eq!(updated["service"], "app");
        assert_eq!(updated["workspaceFolder"], "/workspace");
        let compose_arr = updated["dockerComposeFile"].as_array().unwrap();
        assert_eq!(compose_arr.len(), 2);
        assert_eq!(compose_arr[0], "docker-compose.yml");
        assert_eq!(compose_arr[1], OVERLAY_FILENAME);

        // Key order should be preserved (name should still be first)
        let raw = fs::read_to_string(dc.join("devcontainer.json")).unwrap();
        let name_pos = raw.find("\"name\"").unwrap();
        let service_pos = raw.find("\"service\"").unwrap();
        assert!(name_pos < service_pos);

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn overlay_with_build_config() {
        let compose = ComposeConfig {
            image: None,
            build: Some(crate::config::ComposeBuild {
                context: "..".to_string(),
                dockerfile: Some(".devcontainer/Dockerfile".to_string()),
                target: Some("proxy".to_string()),
            }),
        };
        let overlay = generate_overlay("app", &compose, &[], "172.28.0");
        assert!(overlay.contains("build:"));
        assert!(overlay.contains("context: .."));
        assert!(overlay.contains("dockerfile: .devcontainer/Dockerfile"));
        assert!(overlay.contains("target: proxy"));
        assert!(!overlay.contains("image:"));
    }

    #[test]
    fn overlay_with_default_image() {
        let compose = ComposeConfig::default();
        let overlay = generate_overlay("app", &compose, &[], "172.28.0");
        assert!(overlay.contains("image: ghcr.io/6/devcontainer-guard:latest"));
        assert!(!overlay.contains("build:"));
    }

    #[test]
    fn overlay_includes_proxy_logs_volume() {
        let compose = ComposeConfig::default();
        let overlay = generate_overlay("app", &compose, &[], "172.28.0");
        assert!(overlay.contains("proxy-logs:/var/log/devg"));
        assert!(overlay.contains("volumes:\n  proxy-logs:"));
    }

    #[test]
    fn gitignore_overlay_creates_file() {
        let dir = tempdir("gitignore-create");
        gitignore_overlay(&dir).unwrap();
        let content = fs::read_to_string(dir.join(".gitignore")).unwrap();
        assert!(content.contains(OVERLAY_FILENAME));
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn gitignore_overlay_appends_to_existing() {
        let dir = tempdir("gitignore-append");
        fs::write(dir.join(".gitignore"), "target/\n").unwrap();
        gitignore_overlay(&dir).unwrap();
        let content = fs::read_to_string(dir.join(".gitignore")).unwrap();
        assert!(content.starts_with("target/\n"));
        assert!(content.contains(OVERLAY_FILENAME));
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn gitignore_overlay_is_idempotent() {
        let dir = tempdir("gitignore-idempotent");
        gitignore_overlay(&dir).unwrap();
        gitignore_overlay(&dir).unwrap();
        let content = fs::read_to_string(dir.join(".gitignore")).unwrap();
        let count = content.matches(OVERLAY_FILENAME).count();
        assert_eq!(count, 1);
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn derive_subnet_is_deterministic() {
        let dir = tempdir("subnet-det");
        let a = derive_subnet(&dir);
        let b = derive_subnet(&dir);
        assert_eq!(a, b);
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn derive_subnet_differs_for_different_dirs() {
        let dir1 = tempdir("subnet-a");
        let dir2 = tempdir("subnet-b");
        let s1 = derive_subnet(&dir1);
        let s2 = derive_subnet(&dir2);
        // Not guaranteed to differ for all inputs, but these specific names should
        assert_ne!(s1, s2);
        fs::remove_dir_all(&dir1).unwrap();
        fs::remove_dir_all(&dir2).unwrap();
    }

    #[test]
    fn derive_subnet_in_valid_range() {
        let dir = tempdir("subnet-range");
        let prefix = derive_subnet(&dir);
        let parts: Vec<&str> = prefix.split('.').collect();
        assert_eq!(parts[0], "172");
        let second: u8 = parts[1].parse().unwrap();
        assert!((18..=31).contains(&second));
        let _third: u8 = parts[2].parse().unwrap(); // 0-255, always valid
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn overlay_uses_custom_subnet() {
        let compose = ComposeConfig::default();
        let overlay = generate_overlay("app", &compose, &[], "172.25.42");
        assert!(overlay.contains("172.25.42.2")); // app IP
        assert!(overlay.contains("172.25.42.3")); // sidecar IP
        assert!(overlay.contains("172.25.42.0/24")); // subnet
        assert!(!overlay.contains("172.28.0")); // no old default
    }

    fn tempdir(suffix: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("devg-test-{}-{suffix}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }
}
